### ISSUE TITLE
[5_W0]: Attach DAU Data Collection form to the dashboard

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/DAU#123]
Integrate a [google form](https://forms.gle/A7mAzdsYxgAqy6pdA) in the media details page that allows the DAU Team to add an assessment report and some metadata associated to it in a form.

**Comment by aatmanvaidya** [comment]
form docs
1. [Phoenix.HTML.Form](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html)
2. [Form bindings](https://hexdocs.pm/phoenix_live_view/form-bindings.html)

Other resources
- https://dockyard.com/blog/2024/03/12/dynamically-add-and-remove-embedded-item-inputs-without-javascript
- https://elixirforum.com/t/phoenix-forms-with-custom-grid/30349
- https://www.reddit.com/r/elixir/comments/180glm0/create_a_basic_form_with_phoenix_17/
- simple form in phoenix - https://elixirforum.com/t/settings-phoenix-simple-form/3690
- watch video from `17:51` to see how a simple form is built - https://youtu.be/sJMPLoqIS7M?t=1072 

Book 
- Phoenix Tutorial (Phoenix 1.6) Book - https://thephoenixtutorial.org/book/frontmatter
- Signup form section - https://thephoenixtutorial.org/book/ch7_sign_up#sec-signup_form
- Programming Phoenix ≥ 1.4 - https://media.pragprog.com/titles/phoenix14/feature.pdf
- https://pragprog.com/titles/liveview/programming-phoenix-liveview/

Add fkey in migration
- https://stackoverflow.com/questions/67476330/ecto-referencing-another-schema-during-migration-for-foreign-key-relationship
- https://hexdocs.pm/ecto_sql/Ecto.Migration.html#references/2

put_flash - https://hexdocs.pm/phoenix/Phoenix.Controller.html#put_flash/3

**Comment by aatmanvaidya** [comment]
can we use something like `formex` or its not needed/ overkill for this issue - https://github.com/jakub-zawislak/formex

**Comment by dennyabrain** [comment]
I am generally averse to adding a new non-standard dependency on this project. I have two concerns
1. In favour of using this library : Given that we foresee the form structure to change over time, If this library seems to be simplifying things we can consider using it
2. Against using this library : the last commit seems to be 5 years ago and I am not sure if thats coz the library is complete and doesn't require more work or if its abandoned.

So maybe a starting point would be to investigate if there are more updated libraries like these or if we can dig into its source code to see how they are doing it and cherry pick ideas for our from scratch implementation.

**Comment by aatmanvaidya** [comment]
TODO
- [x] only logged in users of certain role can access this form
- [x] add all google forms fields and options as is to the UI
- [x] When I click on radio label of second theme, I go to primary theme, when I click on the radio button, this issue does not happen
- [x] what comes under my_form and what doesnt?
- [x] ID is getting sent to form_data, what is a good nomenclature for ID?
- [x] what should happen on "ON DELETE" of foreign key - see migration
- [ ] Repo.get() not working on fetch by common id test 
- [x] fix location of create and edit buttons
- [x] add validation to form, some questions are compulsory. 
- [x] add checkbox code
- [x] center the form
- [ ] when we go back from /demo/query, we are directed to the from, how to fix this?

**Comment by aatmanvaidya** [comment]
@dennyabrain I am done with the form end-to-end

- All things should be working as expected
- I have also added validation, because some questions were compulsory and some were not
- I have also integrated the checkbox code you sent, its working very well!

The only thing left now is giving permissions, will also add that by tomorrow. 

Please let me know what all changes to make!

**Comment by aatmanvaidya** [comment]
[Screencast from 30-06-24 06:03:22 PM IST.webm](https://github.com/tattle-made/DAU/assets/56875084/76d09392-9c6a-4591-a71e-f03eb4928d94)
