### ISSUE TITLE
Evaluate Turn

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/DAU#131]

**Comment by aatmanvaidya** [comment]
## Things to Evaluate
1. A conversation builder or support on conversation building - 
is that node based UI we have previously worked with. With `turn` we have to see do they offer something better or atleast as good as what we had previously. One of the issues with prev journey builder had was that the process to import journeys from the staging account to production account was manual. Which defeats the whole purpose of creating a journey in staging. So we'll see how better `turn` is at this.

3. A unified view of all the messages being sent and received from the user, regardless of which API is used - 
What we want is a centralised view of every message sent by the user and tattle, and their delivery status. It should not matter whether i used API `a` or API `b` to send message. If a message is going in and out of our whatsapp account, we need to be able to audit it.

4. Customer Support Quality - response time, response quality

5. documentation quality and ease of navigation etc 

6. Check the developer/user experience with Templates - 
prev BSP template API requires us to match the string exactly!!! as opposed to provide a template id and variables as payload. I would be surprised if turn also has the same string based requirement. but yeah lets evaluate how easy it is to whitelist a template and then incorporate it into our codebase.

## Developer Docs
- Main Doc - https://whatsapp.turn.io/docs
- https://learn.turn.io/l/en/category/urvkyb75wb-for-developers


## rough notes so far

- We are working with Sandboxes, they are prototyping accounts that have most of the functionality of a live WhatsApp line so you can iterate and test seamlessly. To send a message to a sandbox whatsapp line, send join <sandbox-name> to +27600136875.

### journey bot builder
- A trigger node and do the following things
   - on the first visit
   - When a message is received (Example: When “hello” is received...)
   - Before or after an event (Example: 1 week after the first conversation)
   - Specific time (Example: Every Monday at 12:00 PM...)
   - Catch all
- You can add MULTIPLE conditions for a trigger node
- A journey can be `no code` and `code` too.
- Learn how to STORE data from the whatsapp tipline - [read](https://whatsapp.turn.io/docs/build/journeys_results)
- extract the journey data using the Flow Results API in Turn API

### Templates
- using templates is not allowed in a sandbox account
- read the documentation, defining the templates with a variable is same as what it was in gupshup - `{{1}}`
- a template can also have button when we send it (even from code)
- TODO - check if a template message sent to a user can be seen in the chat part of the Turn dashboard. 

### Webhooks
- read this - [New to webhooks?](https://learn.turn.io/l/en/article/3li3isjtg5-new-to-webhooks)
- use RequestBin to inspect a webhook for HTTP request.

**Comment by dennyabrain** [comment]
Continuing in : 
- https://github.com/tattle-made/DAU/issues/137
- https://github.com/tattle-made/DAU/issues/138
