### ISSUE TITLE
Add support for Urdu

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/DAU#141]
# Overview
Add urdu text in the journey builder and whitelist templates in Urdu.

**Comment by aatmanvaidya** [comment]
Attaching screenshots:

![image](https://github.com/user-attachments/assets/fcdef7cc-66c7-445d-a5c4-db660f25d15f)

<br>

![image](https://github.com/user-attachments/assets/b69bbd0d-e5d8-4f8d-b9a9-d9db1dd4e74c)

**Comment by aatmanvaidya** [comment]
working video of the urdu templates

[Screencast from 01-10-24 03:42:19 PM IST.webm](https://github.com/user-attachments/assets/764b1fea-22c5-4f69-b5df-c23ed4f455fc)
