### ISSUE TITLE
DAU secretariat should be able to manually add categories and tags to improve searchability of items

### ISSUE THREAD

**Issue by tarunima** [tattle-made/DAU#58]
At the time of launch, the tags that the DAU team can use for a post will be hard coded. In the long-term, the DAU team should be able to define the tags that a post can be tagged with.

**Comment by areeba-dau** [comment]
@dennyabrain @aatmanvaidya Requesting to add more tags to the dashboard. The new tags are in this sheet [Tags-1](https://docs.google.com/spreadsheets/d/1YLS4MyCmGuvMt95rhAeqgZ9hHor5HM8fZ_KqdtNY-F8/edit#gid=321819565)  The new tags are coloured Blue in column B between row 6 to row 49; total 44 new tags. Thank You!
