### ISSUE TITLE
[20_W1] [Bug]: Fix issues with URL

### ISSUE THREAD

**Issue by tarunima** [tattle-made/DAU#99]
### Describe the bug

-

### Steps to reproduce

-

### Expected behavior

Only the URL should be clickable

### Which operating system are you on?

None

**Comment by dennyabrain** [comment]
Text messages with URLs are correctly rendered on the index page, verification details page and the query detail page.

preview of index page
![Screenshot 2024-04-21 at 15-48-26 DAU · Deepfake Analysis Unit](https://github.com/tattle-made/DAU/assets/1415361/f9d0c310-0bf2-41c3-b1ef-5b43a5baf157)

preview of query detail page
![Screenshot 2024-04-21 at 15-48-36 DAU · Deepfake Analysis Unit](https://github.com/tattle-made/DAU/assets/1415361/6496cc8a-bf4c-4d27-8bef-7874bcfddcb5)

preview of verification detail page
![Screenshot 2024-04-21 at 15-48-48 DAU · Deepfake Analysis Unit](https://github.com/tattle-made/DAU/assets/1415361/bfd08865-6524-4ca9-a453-8b1c26f7a45c)
